VARNAME_CUR_PAGE = "page"
VARNAME_TOTAL = "total"
VARNAME_CUR_INDEX = "i"
VARNAME_INPUT_FILENAME = "infile"
VARNAME_INPUT_FILE_DIR = "indir"
VARNAME_CWD_DIR = "cwd"

VARIABLES = {
    VARNAME_CUR_PAGE: 0,
    VARNAME_TOTAL: 0,
    VARNAME_CUR_INDEX: 0,
    VARNAME_INPUT_FILENAME: "",
    VARNAME_INPUT_FILE_DIR: "",
    VARNAME_CWD_DIR: "",
}
