APP_NAME = "PDF Toolkit"
APP_VERSION = "1.0.0"
APP_AUTHOR = "zimolab"
APP_DESCRIPTION = "A simple PDF toolkit with easy-to-use GUI."
APP_LICENSE = "GPL V3"
APP_REPOSITORY = "https://github.com/zimolab/pdftoolkit"
