DEFAULT_WINDOW_SIZE = (1024, 768)
DEFAULT_OUTPUT_FONT_SIZE = 20
DEFAULT_OUTPUT_FONT_FAMILY = "Arial, sans-serif, Conolas"
DEFAULT_DOCUMENT_FONT_FAMILY = 'Arial, sans-serif, Conolas, "Microsoft YaHei"'
DEFAULT_DOCUMENT_FONT_SIZE = 16
DEFAULT_DOCUMENT_DOCK_WIDTH = 650
DEFAULT_OUTPUT_DOCK_HEIGHT = 230
